/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jvmlearning_jni_Foo */

#ifndef _Included_jvmlearning_jni_Foo
#define _Included_jvmlearning_jni_Foo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jvmlearning_jni_Foo
 * Method:    foo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jvmlearning_jni_Foo_foo
  (JNIEnv *, jclass);

/*
 * Class:     jvmlearning_jni_Foo
 * Method:    bar
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_jvmlearning_jni_Foo_bar__IJ
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     jvmlearning_jni_Foo
 * Method:    bar
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_jvmlearning_jni_Foo_bar__Ljava_lang_String_2Ljava_lang_Object_2
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
